spring.application.name=mysawit-pengiriman

server.port=8084
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${NEON_DB_URL}

spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

grpc.server.port=9094
grpc.client.user-service.address=static://localhost:9091
grpc.client.user-service.negotiationType=PLAINTEXT
grpc.client.harvest-service.address=static://localhost:9092
grpc.client.harvest-service.negotiationType=PLAINTEXT
grpc.client.payment-service.address=static://localhost:9093
grpc.client.payment-service.negotiationType=PLAINTEXT

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
logging.pattern.level=%5p [${spring.application.name}]
